### ISSUE TITLE
Privacy policy:

### ISSUE THREAD

**Issue by auxfuse** [StephenJ2020/soda-apply#30]
* static template
* default render function
* linked from the footer as a quick link

**Comment by StephenJ2020** [comment]
https://gdpr.eu/privacy-notice/ 
 If you are collecting data directly from someone, you have to provide them with your privacy notice at the moment you do so.

According to the GDPR, organizations must provide people with a privacy notice that is:

In a concise, transparent, intelligible, and easily accessible form
Written in clear and plain language, particularly for any information addressed specifically to a child
Delivered in a timely manner
Provided free of charge

If an organization is collecting information from an individual directly, it must include the following information in its privacy notice:

The identity and contact details of the organization, its representative, and its Data Protection Officer
The purpose for the organization to process an individual’s personal data and its legal basis
The legitimate interests of the organization (or third party, where applicable)
Any recipient or categories of recipients of an individual’s data
The details regarding any transfer of personal data to a third country and the safeguards taken
The retention period or criteria used to determine the retention period of the data
The existence of each data subject’s rights
The right to withdraw consent at any time (where relevant)
The right to lodge a complaint with a supervisory authority
Whether the provision of personal data is part of a statutory or contractual requirement or obligation and the possible consequences of failing to provide the personal data
The existence of an automated decision-making system, including profiling, and information about how this system has been set up, the significance, and the consequences

Free Template that was used to create our Privacy Policy:
https://app.privacypolicies.com/download/abfdb529-e3b5-4b65-9b0c-c05ef780733a




Was checking if adding the "title" attribute would improve accessibility but it's a BIG NO NO!!!
https://silktide.com/blog/i-thought-title-text-improved-accessibility-i-was-wrong/ 

A possible alternative if link text isn't descriptive enough seems to be: <span class="sr-only">Enter a more descriptive description here</span> and place between the opening and closing <a> tags!

the above is more or less backed up by A11y:
https://www.a11yproject.com/posts/2013-04-22-title-attributes/
While A11y advises to serve all users with the same info they clarify that the order of precedence for the follow attributes is:
aria-labelledby
aria-label
alt
title
